spring.application.name=emp_mgmt_sys
spring.datasource.url=jdbc:mysql://localhost:3306/emp_mgmt_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
